import type { Lesson } from '@/types/course';

export const LESSON_2_3: Lesson = {
  id: '2.3',
  code: '2.3',
  title: 'Distribuciones de probabilidad',
  objectives: [
    'Explicar qué es la distribución normal y sus propiedades',
    'Identificar los parámetros μ y σ y su efecto en la curva',
    'Calcular probabilidades usando la distribución normal',
    'Interpretar el teorema 68-95-99.7',
    'Calcular y interpretar puntuaciones Z',
  ],
  prerequisites: ['2.2 Estadística descriptiva'],
  theory: [
    {
      id: '2.3-t1',
      type: 'text',
      title: '¿Qué es la distribución normal?',
      content: 'La distribución normal (también llamada gaussiana o de Laplace-Gauss) es la distribución de probabilidad continua más importante en estadística. Muchos fenómenos naturales la siguen: estaturas, pesos, presión arterial, errores de medición, puntuaciones en exámenes.',
    },
    {
      id: '2.3-t2',
      type: 'text',
      title: '¿Por qué existe?',
      content: 'Existe por el Teorema del Límite Central: cuando sumamos muchas variables aleatorias independientes, su distribución tiende a ser normal, sin importar la distribución original. Esto la convierte en la base de la inferencia estadística.',
    },
    {
      id: '2.3-t3',
      type: 'formula',
      title: 'Función de densidad de probabilidad',
      content: 'La forma matemática de la campana de Gauss:',
      formula: 'f(x) = (1 / (σ√(2π))) · e^(-(x-μ)² / (2σ²))',
    },
    {
      id: '2.3-t4',
      type: 'list',
      title: 'Parámetros fundamentales',
      items: [
        'μ (media): determina el centro de la campana. Es el valor más probable.',
        'σ (desviación estándar): determina el ancho de la campana. Mayor σ = más dispersión.',
        'σ² (varianza): es el cuadrado de la desviación estándar.',
      ],
    },
    {
      id: '2.3-t5',
      type: 'note',
      title: 'La regla 68-95-99.7',
      content: 'En cualquier distribución normal: aproximadamente el 68% de los datos caen dentro de ±1σ de la media, el 95% dentro de ±2σ, y el 99.7% dentro de ±3σ. Esta regla permite hacer estimaciones rápidas.',
    },
    {
      id: '2.3-t6',
      type: 'warning',
      title: 'Errores frecuentes',
      content: 'No confundir la distribución normal con la uniforme (donde todos los valores son igualmente probables). Tampoco confundir varianza con desviación estándar: la desviación estándar está en las mismas unidades que los datos.',
    },
    {
      id: '2.3-t7',
      type: 'text',
      title: 'Ejemplo real',
      content: 'Supongamos que las estaturas de adultos siguen N(μ=170cm, σ=8cm). Esto significa que la estatura promedio es 170cm, y la mayoría (68%) de personas miden entre 162cm y 178cm.',
    },
  ],
  visualExamples: [
    {
      id: '2.3-v1',
      type: 'simulation',
      title: 'Distribución normal interactiva',
      description: 'Modifica la media (μ) y la desviación estándar (σ) para observar cómo cambia la forma de la curva en tiempo real.',
      chartType: 'distribution',
      interactive: true,
      parameters: [
        { id: 'mu', label: 'Media (μ)', min: -5, max: 5, step: 0.1, defaultValue: 0 },
        { id: 'sigma', label: 'Desviación estándar (σ)', min: 0.1, max: 3, step: 0.1, defaultValue: 1 },
      ],
    },
  ],
  activities: [
    {
      id: '2.3-a1',
      type: 'multiple-choice',
      title: 'Identificar parámetros',
      question: 'En una distribución N(μ=50, σ=10), ¿qué representa el valor 50?',
      options: [
        { id: 'a', text: 'La desviación estándar' },
        { id: 'b', text: 'La media (centro de la distribución)' },
        { id: 'c', text: 'El valor mínimo' },
        { id: 'd', text: 'La varianza' },
      ],
      correctAnswer: 'b',
      explanation: 'El primer parámetro de N(μ, σ) es la media (μ), que indica el centro de la distribución. Es el valor alrededor del cual se concentran los datos.',
      conceptLinked: 'Parámetros de la distribución normal',
    },
    {
      id: '2.3-a2',
      type: 'multiple-select',
      title: 'Propiedades de la normal',
      question: '¿Cuáles de las siguientes son propiedades de la distribución normal? (Selecciona todas las que apliquen)',
      options: [
        { id: 'a', text: 'Es simétrica respecto a la media' },
        { id: 'b', text: 'La media, mediana y moda son iguales' },
        { id: 'c', text: 'El área total bajo la curva es 1' },
        { id: 'd', text: 'Solo toma valores enteros' },
        { id: 'e', text: 'Se define por μ y σ' },
      ],
      correctAnswer: ['a', 'b', 'c', 'e'],
      explanation: 'La distribución normal es simétrica, media=mediana=moda, el área total es 1 (es una distribución de probabilidad), y se define completamente por μ y σ. No solo toma valores enteros: es continua.',
      conceptLinked: 'Propiedades de la distribución normal',
    },
    {
      id: '2.3-a3',
      type: 'numeric',
      title: 'Cálculo de probabilidad',
      question: 'Si X ~ N(100, 15), según la regla 68-95-99.7, aproximadamente ¿qué porcentaje de datos está entre 85 y 115? (Responde con el número, ej: 68)',
      correctAnswer: '68',
      explanation: '85 = 100 - 15 = μ - σ, y 115 = 100 + 15 = μ + σ. Según la regla 68-95-99.7, aproximadamente el 68% de los datos caen dentro de ±1σ de la media.',
      conceptLinked: 'Regla 68-95-99.7',
    },
  ],
  guidedPractice: {
    id: '2.3-gp',
    title: 'Calcular probabilidades con Python',
    objective: 'Usar Python para calcular P(X > 120) dado X ~ N(μ=100, σ=15)',
    dataset: ' heights.csv',
    steps: [
      {
        id: '2.3-gp-1',
        instruction: 'Importa la librería scipy.stats para acceder a funciones de distribución.',
        codeTemplate: 'from scipy import stats\nimport numpy as np',
        explanation: 'scipy.stats.norm nos permite trabajar con la distribución normal.',
        hints: ['scipy tiene un módulo llamado stats', 'La distribución normal está en stats.norm'],
      },
      {
        id: '2.3-gp-2',
        instruction: 'Define los parámetros de la distribución.',
        codeTemplate: 'mu = 100\nsigma = 15',
        explanation: 'Establecemos los parámetros de nuestra distribución N(100, 15).',
        hints: ['Asigna los valores a variables mu y sigma'],
      },
      {
        id: '2.3-gp-3',
        instruction: 'Calcula P(X > 120) usando la función CDF.',
        codeTemplate: 'prob = 1 - stats.norm.cdf(120, loc=mu, scale=sigma)\nprint(f"P(X > 120) = {prob:.4f}")',
        explanation: 'P(X > x) = 1 - P(X ≤ x) = 1 - CDF(x). La función CDF retorna la probabilidad acumulada.',
        hints: ['Recuerda que P(X > x) = 1 - P(X ≤ x)', 'Usa stats.norm.cdf con loc=mu y scale=sigma'],
      },
    ],
    language: 'python',
  },
  challenge: {
    id: '2.3-ch',
    title: 'Reto: Salarios corporativos',
    description: 'Los ingresos anuales de una empresa siguen una distribución N(μ=$50,000, σ=$12,000). Calcula: (a) ¿Qué porcentaje de empleados gana más de $70,000? (b) ¿Cuál es el salario del 10% superior? (c) ¿Qué porcentaje gana entre $38,000 y $62,000?',
    language: 'python',
    codeTemplate: 'from scipy import stats\nimport numpy as np\n\nmu = 50000\nsigma = 12000\n\n# (a) P(X > 70000)\n# (b) Percentil 90\n# (c) P(38000 < X < 62000)',
    expectedApproach: 'Usar stats.norm.cdf y stats.norm.ppf para calcular probabilidades y percentiles.',
    evaluationCriteria: [
      'Correcta aplicación de P(X > x) = 1 - CDF(x)',
      'Correcto uso de ppf para percentiles',
      'Interpretación adecuada de resultados',
      'Código limpio y documentado',
    ],
  },
  assessment: {
    id: '2.3-assess',
    passingScore: 70,
    questions: [
      {
        id: '2.3-q1',
        type: 'multiple-choice',
        text: '¿Qué representa la desviación estándar (σ) en una distribución normal?',
        options: [
          { id: 'a', text: 'El centro de la distribución' },
          { id: 'b', text: 'La dispersión de los datos respecto a la media' },
          { id: 'c', text: 'El valor máximo de la función de densidad' },
          { id: 'd', text: 'El número total de observaciones' },
        ],
        correctAnswer: 'b',
        explanation: 'La desviación estándar mide la dispersión. Un σ mayor indica que los datos están más alejados de la media.',
        conceptLinked: 'Parámetros de la distribución normal',
        difficulty: 'easy',
      },
      {
        id: '2.3-q2',
        type: 'interpretation',
        text: 'Si X ~ N(170, 8), ¿aproximadamente qué porcentaje de personas mide entre 162cm y 178cm?',
        options: [
          { id: 'a', text: '50%' },
          { id: 'b', text: '68%' },
          { id: 'c', text: '95%' },
          { id: 'd', text: '99.7%' },
        ],
        correctAnswer: 'b',
        explanation: '162 = 170 - 8 = μ - σ y 178 = 170 + 8 = μ + σ. Por la regla 68-95-99.7, el 68% está dentro de ±1σ.',
        conceptLinked: 'Regla 68-95-99.7',
        difficulty: 'easy',
      },
      {
        id: '2.3-q3',
        type: 'numeric',
        text: 'Si Z ~ N(0, 1), calcula P(Z > 1.96). Redondea a 4 decimales.',
        correctAnswer: 0.0250,
        explanation: 'P(Z > 1.96) = 1 - Φ(1.96) = 1 - 0.9750 = 0.0250. Esto corresponde al 2.5% superior.',
        conceptLinked: 'Cálculo de Z-scores y probabilidades',
        difficulty: 'medium',
      },
      {
        id: '2.3-q4',
        type: 'numeric',
        text: 'Una prueba tiene media 500 y desviación estándar 100. ¿Cuál es la puntuación Z de alguien que sacó 650?',
        correctAnswer: 1.5,
        explanation: 'Z = (X - μ) / σ = (650 - 500) / 100 = 1.5. Esta persona está 1.5 desviaciones estándar por encima de la media.',
        conceptLinked: 'Puntuaciones Z',
        difficulty: 'medium',
      },
      {
        id: '2.3-q5',
        type: 'multiple-choice',
        text: '¿Qué ocurre con la curva normal cuando aumentas σ manteniendo μ constante?',
        options: [
          { id: 'a', text: 'La curva se vuelve más alta y estrecha' },
          { id: 'b', text: 'La curva se vuelve más baja y ancha' },
          { id: 'c', text: 'La curva se desplaza a la derecha' },
          { id: 'd', text: 'La curva no cambia' },
        ],
        correctAnswer: 'b',
        explanation: 'Al aumentar σ, los datos se dispersan más, haciendo la curva más plana y ancha. El área total siempre es 1.',
        conceptLinked: 'Efecto de los parámetros',
        difficulty: 'medium',
      },
    ],
  },
  competencies: ['Distribución normal', 'Probabilidad', 'Cálculo de Z-scores', 'Regla 68-95-99.7'],
};
